
export const LOAD_PROJECTS_START = "LOAD_PROJECTS_START";
export const LOAD_PROJECTS_SUCCESS = "LOAD_PROJECTS_SUCCESS";
export const LOAD_PROJECTS_ERROR = "LOAD_PROJECTS_ERROR";

export const LOAD_PROJECT_DETAIL_START = "LOAD_PROJECT_DETAIL_START";
export const LOAD_PROJECT_DETAIL_SUCCESS = "LOAD_PROJECT_DETAIL_SUCCESS";
export const LOAD_PROJECT_DETAIL_ERROR = "LOAD_PROJECT_DETAIL_ERROR";

export const LOAD_NEWS_START = "LOAD_NEWS_START";
export const LOAD_NEWS_SUCCESS = "LOAD_NEWS_SUCCESS";
export const LOAD_NEWS_ERROR = "LOAD_NEWS_ERROR";

export const LOAD_CAREERS_START = "LOAD_CAREERS_START";
export const LOAD_CAREERS_SUCCESS = "LOAD_CAREERS_SUCCESS";
export const LOAD_CAREERS_ERROR = "LOAD_CAREERS_ERROR";

